<h1>Editar categorías</h1>
<div class="row">
    <div class="col-sm-6">

        <form action="<?php echo APP_URL . "categorias/editar"; ?>" method="POST">
            <input type="hidden" name="id" value="<?php echo $this->categoria["id"]; ?>">
            <p>
                <label for="name">Nombre</label>
                <input type="text" name="name" value="<?php echo $this->categoria["name"]; ?>" class="form-control">
            </p>
            <p>
                <input type="submit" value="Guardar categoría" class="btn-primary" onclick="if(!confirm('¿Desea guardar cambios?')) return false;">
            </p>
        </form>
    </div>
</div>