<h2>Agregar cuenta</h2>
<div class="row">
    <div class="col-sm-6">
        <form action="<?php echo APP_URL . "cuentas/agregar"; ?>" method="POST">
            <p>
                <label for="name">Nombre</label>
                <input type="text" name="name" class="form-control">
            </p>
            <p>
                <input class="btn-primary" type="submit" value="Guardar cuenta" onclick="if(!confirm('¿Desea continuar con el guardado?')) return false;">
            </p>
        </form>
    </div>
</div>
</div>