<div class="row">
    <div class="col-sm-12">
        <ul class="nav nav-pills nav-justified">
            <li role="presentation"><a href="<?php echo APP_URL . "transacciones/index"; ?>">Transacciones</a></li>
            <li role="presentation"><a href="<?php echo APP_URL . "categorias/index"; ?>">Categorías</a></li>
            <li role="presentation" class="active"><a href="<?php echo APP_URL . "cuentas/index"; ?>">Cuentas</a></li>
        </ul>
    </div>
    <div class="col-sm-8"><h3>Listado de cuentas</h3></div>
</div>

</br>

<div class="table-responsive">
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Acción</th>
        </tr>
        <?php foreach ($this->cuentas as $cuenta): ?>
            <tr>
                <td><?php echo $cuenta["id"]; ?></td>
                <td><?php echo $cuenta["name"]; ?></td>
                <td>
                    <a href="<?php echo APP_URL . "cuentas/editar/" . $cuenta["id"]; ?>">
                        <span class="glyphicon glyphicon-edit"> </span>
                    </a> |
                    <a onclick="if(!confirm('¿Desea eliminar esta cuenta?')) return false;"
                       href="<?php echo APP_URL . "cuentas/eliminar/" . $cuenta["id"]; ?>">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
<div class="col-sm-8">
    <a href="<?php echo APP_URL . "cuentas/agregar"; ?>">
        <button type="button" class="btn-primary add">
            <span class="glyphicon glyphicon-plus">&nbsp;Cuenta</span>
        </button>
    </a>
</div>
</div>